class_name ChallengeText
extends RefCounted

const TEXT := {
	"ru": {
		"fall_respawn": "Земля вытолкнула вас обратно на тропу.",
		"pause": "ПАУЗА\nEsc или кнопка паузы — продолжить",
		"controls": "WASD — движение  •  Shift — бег  •  Мышь/свайп — обзор  •  E/Пробел — действие  •  Esc/кнопка паузы",
		"start": "НАЧАТЬ ИСПЫТАНИЕ",
		"menu": "К ВЫБОРУ УРОВНЕЙ",
		"next": "СЛЕДУЮЩЕЕ ИСПЫТАНИЕ",
		"restart": "ПОВТОРИТЬ УРОВЕНЬ",
		"intro_hint": "Сначала печати. Проклятые чучела очищаются солнечным импульсом.",
		"fire_need_seals": "Огонь молчит: соберите все солнечные печати.",
		"fire_need_curses": "Огонь опутан порчей: очистите все чучела импульсом.",
		"well_empty": "Солнечный колодец уже опустел.",
		"well_used": "Колодец восстановил вас, но его вспышка созвала Стражей.",
		"pulse_locked": "Импульс проснётся после первой печати.",
		"pulse_cooldown": "Импульс восстановится через %.1f с.",
		"pulse_tired": "Не хватает сил для импульса.",
		"pulse_cleanse": "Порча рассеяна: %d/%d. Отброшено Стражей: %d.",
		"pulse_hit": "Импульс отбросил Стражей: %d.",
		"pulse_miss": "Импульс ушёл в пустоту. Подойдите ближе к цели.",
		"fire_lit": "Курганный огонь %d/%d зажжён. Стражи услышали его.",
		"gate_timed": "Ворота открыты. До полного затмения — %d секунд!",
		"gate_open": "Последний огонь горит. Ворота открыты — уходите на север!",
		"overtime": "Затмение завершилось. Свет больше не лечит, но выход ещё открыт!",
		"seal_found": "Печать %d/%d снята. Проснулись Стражи: %d/%d.",
		"wounded": "Вы ранены. Свет лечит, колодец восстанавливает силы.",
		"charge": "Янтарный след: уходите с линии рывка!",
		"wail": "Крик плакальщицы поднял остальных!",
		"enemy_warden": "Стражи",
		"enemy_husk": "Ползуны",
		"enemy_stalker": "Соглядатаи",
		"enemy_ringer": "Плакальщицы",
		"enemy_sentinel": "Сторожа поля",
		"intro_enemy_kinds": "
На карте: %s.",
		"gate_locked": "Ворота держат незавершённые испытания.",
		"level_complete_objective": "УРОВЕНЬ %d ПРОЙДЕН",
		"level_complete_title": "ИСПЫТАНИЕ ПРОЙДЕНО",
		"result": "Время: %s\nУдары: %d   •   Импульсы: %d   •   Возвращения: %d\nОценка: %s",
		"death_respawn": "Солнце вернуло вас к началу испытания.",
		"death_title": "У ВАС ЗАБРАЛИ ЖИЗНЬ",
		"death_offer": "Стражи оставили вас у праздничной тропы. Посмотрите рекламу Яндекса, чтобы вернуться в это испытание с полной жизнью, или начните уровень заново.",
		"reward_life": "СМОТРЕТЬ РЕКЛАМУ — ВЕРНУТЬ ЖИЗНЬ",
		"reward_yandex_only": "ВОЗРОЖДЕНИЕ ДОСТУПНО В ЯНДЕКС ИГРАХ",
		"reward_loading": "ОТКРЫВАЕМ РЕКЛАМУ…",
		"reward_wait": "Просмотрите рекламу до конца — после подтверждения Яндекса жизнь будет возвращена.",
		"reward_not_completed": "Просмотр не был завершён. Жизнь не возвращена — можно попробовать ещё раз или начать уровень заново.",
		"reward_revived": "Солнце вернуло вам жизнь. Стражи ненадолго оглушены.",
		"status_rift": "РАЗЛОМ ВЫТЯГИВАЕТ ЖИЗНЬ И СИЛЫ",
		"status_guardian": "ВРАГ СОВСЕМ РЯДОМ",
		"status_overtime": "ПОЛНОЕ ЗАТМЕНИЕ — ЛЕЧЕНИЯ НЕТ",
		"status_sun": "СВЕТ ЛЕЧИТ",
		"status_shadow": "В ТЕНИ СТРАЖИ БЫСТРЕЕ",
		"prompt_well": "E / ПРОБЕЛ — СОЛНЕЧНЫЙ КОЛОДЕЦ",
		"prompt_well_empty": "КОЛОДЕЦ ОПУСТЕЛ",
		"prompt_curse": "E / ПРОБЕЛ — ОЧИСТИТЬ РИТУАЛЬНОЕ ЧУЧЕЛО",
		"trap_caught": "Солнечная ловушка удержала Стража. Поймано: %d.",
		"prompt_fire": "E / ПРОБЕЛ — ЗАЖЕЧЬ КУРГАННЫЙ ОГОНЬ",
		"objective_seals": "ПЕЧАТИ  %d / %d",
		"secondary_counts": "Порча: %d/%d  •  Огни: %d/%d",
		"objective_curses": "ОЧИСТИТЕ ЧУЧЕЛА ИМПУЛЬСОМ  %d / %d",
		"secondary_curses": "Подойдите к фиолетовому чучелу и используйте E / Пробел",
		"objective_fires": "КУРГАННЫЕ ОГНИ  %d / %d",
		"secondary_fires": "Подойдите к огню и нажмите E / Пробел",
		"objective_exit": "ВОРОТА ОТКРЫТЫ  •  УЙДИТЕ НА СЕВЕР",
		"eclipse_time": "До затмения: %02d",
		"eclipse_full": "Полное затмение",
		"exit_clear": "Северный проход свободен",
		"pulse_none": "ИМПУЛЬС: НЕТ ПЕЧАТИ",
		"pulse_wait": "ИМПУЛЬС: %.1f С",
		"pulse_low": "ИМПУЛЬС: НЕТ СИЛ",
		"pulse_ready": "ИМПУЛЬС: ГОТОВ",
		"intro_counts": "%d печатей • %d огней • %d врагов",
		"intro_curses": " • %d проклятых чучел",
		"intro_rifts": "\nИзбегайте фиолетовых разломов: они вытягивают жизнь и силы.",
		"intro_eclipse": "\nПосле последнего огня начнётся затмение. Опоздание отключает лечение.",
		"intro_well": "\nСолнечный колодец можно использовать один раз — вспышка привлечёт врагов.",
		"level_title": "УРОВЕНЬ %d — %s",
	},
	"en": {
		"fall_respawn": "The earth pushed you back onto the path.",
		"pause": "PAUSED\nEsc or pause button — continue",
		"controls": "WASD — move  •  Shift — run  •  Mouse/swipe — look  •  E/Space — action  •  Esc/pause button",
		"start": "START CHALLENGE",
		"menu": "LEVEL SELECT",
		"next": "NEXT CHALLENGE",
		"restart": "RETRY LEVEL",
		"intro_hint": "Find the seals first. Cleanse cursed effigies with the sun pulse.",
		"fire_need_seals": "The fire is silent: collect every sun seal.",
		"fire_need_curses": "Corruption binds the fire: cleanse every effigy with the pulse.",
		"well_empty": "The sun well is empty.",
		"well_used": "The well restored you, but its flare summoned the Guardians.",
		"pulse_locked": "The pulse awakens after the first seal.",
		"pulse_cooldown": "Pulse ready in %.1f s.",
		"pulse_tired": "Not enough stamina for a pulse.",
		"pulse_cleanse": "Corruption cleared: %d/%d. Guardians repelled: %d.",
		"pulse_hit": "Guardians repelled: %d.",
		"pulse_miss": "The pulse found nothing. Move closer to the target.",
		"fire_lit": "Mound fire %d/%d is lit. The Guardians heard it.",
		"gate_timed": "The gate is open. Total eclipse in %d seconds!",
		"gate_open": "The final fire burns. The gate is open — go north!",
		"overtime": "The eclipse is complete. Light no longer heals, but the exit is still open!",
		"seal_found": "Seal %d/%d released. Guardians awake: %d/%d.",
		"wounded": "You are wounded. Sunlight heals; the well restores stamina.",
		"charge": "Amber trail: step away from the charge line!",
		"wail": "The Weeper's cry roused the others!",
		"enemy_warden": "Guardians",
		"enemy_husk": "Crawlers",
		"enemy_stalker": "Watchers",
		"enemy_ringer": "Weepers",
		"enemy_sentinel": "Field Wardens",
		"intro_enemy_kinds": "
On this map: %s.",
		"gate_locked": "Unfinished trials hold the gate shut.",
		"level_complete_objective": "LEVEL %d COMPLETE",
		"level_complete_title": "CHALLENGE COMPLETE",
		"result": "Time: %s\nHits: %d   •   Pulses: %d   •   Returns: %d\nGrade: %s",
		"death_respawn": "The sun returned you to the start of the challenge.",
		"death_title": "YOUR LIFE WAS TAKEN",
		"death_offer": "The Guardians left you beside the festival path. Watch a Yandex ad to return to this challenge with full health, or restart the level.",
		"reward_life": "WATCH AD — RESTORE LIFE",
		"reward_yandex_only": "REVIVAL IS AVAILABLE ON YANDEX GAMES",
		"reward_loading": "OPENING AD…",
		"reward_wait": "Watch the ad to the end. Your life is restored only after Yandex confirms the reward.",
		"reward_not_completed": "The ad was not completed. No life was granted — try again or restart the level.",
		"reward_revived": "The sun restored your life. The Guardians are briefly stunned.",
		"status_rift": "THE RIFT DRAINS HEALTH AND STAMINA",
		"status_guardian": "AN ENEMY IS VERY CLOSE",
		"status_overtime": "TOTAL ECLIPSE — NO HEALING",
		"status_sun": "SUNLIGHT HEALS",
		"status_shadow": "GUARDIANS ARE FASTER IN SHADOW",
		"prompt_well": "E / SPACE — USE SUN WELL",
		"prompt_well_empty": "THE WELL IS EMPTY",
		"prompt_curse": "E / SPACE — CLEANSE RITUAL EFFIGY",
		"trap_caught": "The sun snare bound a Guardian. Trapped: %d.",
		"prompt_fire": "E / SPACE — LIGHT MOUND FIRE",
		"objective_seals": "SEALS  %d / %d",
		"secondary_counts": "Corruption: %d/%d  •  Fires: %d/%d",
		"objective_curses": "CLEANSE EFFIGIES WITH THE PULSE  %d / %d",
		"secondary_curses": "Approach a violet effigy and press E / Space",
		"objective_fires": "MOUND FIRES  %d / %d",
		"secondary_fires": "Approach a fire and press E / Space",
		"objective_exit": "THE GATE IS OPEN  •  GO NORTH",
		"eclipse_time": "Eclipse in: %02d",
		"eclipse_full": "Total eclipse",
		"exit_clear": "Northern passage is clear",
		"pulse_none": "PULSE: NO SEAL",
		"pulse_wait": "PULSE: %.1f S",
		"pulse_low": "PULSE: LOW STAMINA",
		"pulse_ready": "PULSE: READY",
		"intro_counts": "%d seals • %d fires • %d enemies",
		"intro_curses": " • %d cursed effigies",
		"intro_rifts": "\nAvoid violet rifts: they drain health and stamina.",
		"intro_eclipse": "\nAn eclipse begins after the final fire. Running late disables healing.",
		"intro_well": "\nThe sun well can be used once — its flare attracts enemies.",
		"level_title": "LEVEL %d — %s",
	},
}

static func get_text(key: String, language: String) -> String:
	var selected := "ru" if language.begins_with("ru") else "en"
	return String(TEXT[selected].get(key, key))
